apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - name: http
      port: 8000
      nodePort: 8000
  type: NodePort
