apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: gateway-service
    spec: # pod spec
      containers:
        - name: gateway-service
          image: thefoothing/codecurate:gateway_service # image we pushed
          ports:
            - containerPort: 3000
